name: .NET

on:
  push:
    branches: [master]
    tags:
      - "**"
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') == true

    steps:
      - name: Set version from tag
        run: |
          VERSION=$(echo $GITHUB_REF | sed -e 's/refs\/tags\///g')
          echo $VERSION >> $GITHUB_ENV

      - name: Pack
        run: dotnet build --configuration Release /p:Version=$VERSION

      - name: Push
        run: dotnet nuget push --api-key $NUGET_TOKEN --source https://api.nuget.org/v3/index.json ./bin/Release/*.nupkg
        env:
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
